import json
import numpy as np
from sklearn.linear_model import LogisticRegression  # logistic regression
from sklearn.feature_extraction.text import CountVectorizer  # bag-of-words
from sklearn.ensemble import RandomForestClassifier  # random forest

# dimensionality reduction
from sklearn.decomposition import PCA

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn import svm  # support vector machines, SVM

# ALTERNATIVE METHOD TO BAG-OF-WORDS (TF-IDF)
from sklearn.feature_extraction.text import TfidfVectorizer

# to split into test and training data
import random

# confusion matrix and accuracy
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

# logistic regression parameter tuning
from sklearn.model_selection import GridSearchCV

# import models
import pickle

# SMOTE
from imblearn.over_sampling import SMOTE
from collections import Counter

# BIG DATASET
path1 = 'domain1_train.json'
path2 = 'domain2_train.json'
kaggle_test_set = 'test_set.json'

# SMALLER DATASET
path3 = 'domain1_80_percent.json'
path4 = 'domain1_20_percent.json'

path5 = 'domain2_80_percent.json'
path6 = 'domain2_20_percent.json'

path7 = 'domain3_80_percent.json'
path8 = 'domain3_20_percent.json'


# Issues
# 1) Datasets drawn from distinct domains
# 2) Label imbalance

# The machine-generated data from domain2 was generated by 7 different models, while domain1 only uses one model,
# which is distinct from the models in domain2. You may choose to use this fact in training.

def readfile(file):
    list = []
    data = open(file, 'r')
    for line in data:
        if type(line) != None:
            list.append(json.loads(line))
    return list


def split_data(dataset):
    # Split the data into training and testing sets (80% training, 20% testing in this example)
    # Shuffle the data randomly
    random.shuffle(dataset)

    # Calculate the split index
    split_index = int(0.2 * len(dataset))

    # Split the data into two separate lists
    train_lista = dataset[split_index:]
    test_lista = dataset[:split_index]
    training_data = Dataset(train_lista)
    test_data = Dataset(test_lista)
    return training_data, test_data


def split_predictions(predictions,true_labels):
    import random

    # Your lists
    #predictions = [[1, 0, 1, 1, 1, 0], [1, 0, 1, 1, 1, 1], [1, 0, 1, 1, 1, 1]]  # List of predictions
    #true_labels = [1, 0, 1, 1, 1, 0]  # List of true labels

    # Determine the number of samples for the split
    total_samples = len(predictions[0])
    split_ratio = 0.8  # 80% for training, 20% for validation
    num_samples_train = int(total_samples * split_ratio)
    num_samples_validation = total_samples - num_samples_train

    # Create new empty lists for training predictions and labels
    new_predictions = [[] for _ in range(len(predictions))]
    new_true_labels = []

    # Create new empty lists for validation predictions and labels
    validation_predictions = [[] for _ in range(len(predictions))]
    validation_true_labels = []

    # Randomly shuffle the indices to ensure randomness
    indices = list(range(total_samples))
    random.shuffle(indices)

    # Split the data into training and validation sets
    for index in indices[:num_samples_train]:
        for i, sublist in enumerate(predictions):
            new_predictions[i].append(sublist[index])
        new_true_labels.append(true_labels[index])

    for index in indices[num_samples_train:]:
        for i, sublist in enumerate(predictions):
            validation_predictions[i].append(sublist[index])
        validation_true_labels.append(true_labels[index])

    return new_predictions,new_true_labels,validation_predictions,validation_true_labels


class Dataset():
    # DATASET 1:
    # label 0 = machine generated --> model 7
    # label 1 = human generated ---> model 8

    # DATASET 2:
    # label 0 = machine generated --> model = 0-6
    # label 1 = human generated --> model 8

    def __init__(self, lista):
        self.list = lista
        self.values = []
        self.labels = []
        self.models = []
        self.process()

    def process(self):
        for element in self.list:
            self.values.append(element["text"])
            if "label" in element:  # if there is labels, saves them in variable
                self.labels.append(element["label"])

                # To add the different models
                if "model" in element:  # för dataset 2, om det finns en
                    self.models.append(element["model"])
                elif element["label"] == 0:  # om machingenererad i dataset 1
                    self.models.append(7)
                elif element["label"] == 1:  # om human generated
                    self.models.append(8)


class VectorRepresentation():

    def __init__(self, train_data, test_data, smote=None, vectorizer=None, pca=None, scaler=None):
        self.train_data = train_data
        self.test_data = test_data
        self.vectorizer = vectorizer
        self.scaler = scaler
        self.pca = pca
        # self.train_x, self.test_x = self.bag_of_words()
        if smote != None:
            self.undersample()
            self.train_x, self.test_x = self.tf_idf()
            self.oversample()
        else:
            self.train_x, self.test_x = self.tf_idf()
        self.train_x_red, self.test_x_red = self.dimensionality_reduction()
        self.train_x_scaling, self.test_x_scaling = self.rescaling()

    def bag_of_words(self):
        # BAG OF WORDS
        train_data_str = [' '.join(map(str, row)) for row in self.train_data.values]
        test_data_str = [' '.join(map(str, row)) for row in self.test_data.values]
        self.vectorizer = CountVectorizer()
        X_train = self.vectorizer.fit_transform(train_data_str)
        X_test = self.vectorizer.transform(test_data_str)
        train_X = X_train.toarray()
        test_X = X_test.toarray()
        return train_X, test_X

    def tf_idf(self):
        # Create TF-IDF vectors
        train_X = None
        if self.vectorizer == None:
            train_data_str = [' '.join(map(str, row)) for row in self.train_data.values]
            self.vectorizer = TfidfVectorizer()
            X_train = self.vectorizer.fit_transform(train_data_str)
            train_X = X_train.toarray()

        test_data_str = [' '.join(map(str, row)) for row in self.test_data.values]
        X_test = self.vectorizer.transform(test_data_str)
        test_X = X_test.toarray()
        return train_X, test_X


    def undersample(self):
        print('UNDERSAMPLING')
        domain_counts = Counter(self.train_data.models)
        print(domain_counts)
        smallest_value = min(domain_counts.values())

        # Assuming you have your data in self.values and self.models
        x_values = self.train_data.values
        y_values = np.array(self.train_data.models)

        # Find the indices of classes that need undersampling (all classes except 8)
        classes_to_undersample = np.unique(y_values[y_values != 8])

        # Set the desired number of samples for each of these classes
        desired_samples = smallest_value

        # Initialize empty lists to store the undersampled data
        x_resampled = []
        y_resampled = []

        # Extract and append all samples from class 8
        class_8_indices = np.where(y_values == 8)[0]
        x_resampled.extend([x_values[i] for i in class_8_indices])
        y_resampled = np.hstack([y_resampled, y_values[class_8_indices]])

        # Undersample the selected classes
        for class_label in classes_to_undersample:
            class_indices = np.where(y_values == class_label)[0]

            # Randomly select the desired number of samples if there are more
            if len(class_indices) > desired_samples:
                sampled_indices = np.random.choice(class_indices, desired_samples, replace=False)
            else:
                # If there are fewer samples than desired, include all of them
                sampled_indices = class_indices

            # Append the selected samples to the resampled data
            x_resampled.extend([x_values[i] for i in sampled_indices])
            y_resampled = np.hstack([y_resampled, y_values[sampled_indices]])

        # Check the distribution of the classes in the undersampled dataset

        model_counts = Counter(y_resampled)
        # Iterate through the unique elements and their counts
        for element, count in model_counts.items():
            print(f'Number of {element}s: {count}')

        print('\n')
        updated_list = [1 if x == 8 else 0 for x in y_resampled]
        label_counts = Counter(updated_list)
        for element, count in label_counts.items():
            print(f'Number of {element}s: {count}')

        # UPDATE OUR MODEL PARAMETERS
        self.train_data.values = x_resampled
        self.train_data.models = y_resampled
        self.train_data.labels = updated_list

    def oversample(self):
        print('OVERSAMPLING')
        smote = SMOTE(random_state=42)

        # Fit and apply SMOTE to the dataset
        x_smote, y_smote = smote.fit_resample(self.train_x, self.train_data.labels)

        # Ensure self.train_data.models has the same length as y_smote
        while len(self.train_data.models) < len(y_smote):
            self.train_data.models = np.append(self.train_data.models, 8)

        # EFTER SMOTE
        print('\n')
        element_counts = Counter(y_smote)
        # Iterate through the unique elements and their counts
        for element, count in element_counts.items():
            print(f'Number of {element}s: {count}')

        self.train_x = x_smote
        self.train_data.labels = y_smote

    def dimensionality_reduction(self):
        n_components = 100  # Number of components to keep (adjust as needed)
        train_x_red = None
        if self.pca == None:  # and self.train_x != None: # SKA DET VARA SÅHÄR?!?!?!?!?!!
            self.pca = PCA(n_components=n_components)
            train_x_red = self.pca.fit_transform(self.train_x)
        test_x_red = self.pca.fit_transform(self.test_x)
        return train_x_red, test_x_red

    def rescaling(self):
        train_x_scaled = None
        if self.scaler == None:
            self.scaler = MinMaxScaler(feature_range=(-1, 1))
            train_x_scaled = self.scaler.fit_transform(self.train_x_red)
        test_x_scaled = self.scaler.transform(self.test_x_red)
        return train_x_scaled, test_x_scaled

    def add_new_feature(self, new_feature):  # new features ska predictas för testdatan!!!
        if self.train_data != None:
            training_mod_arr = np.array(self.train_data.models).reshape(-1, 1)
            self.train_x = np.hstack((self.train_x, training_mod_arr))
        test_mod_arr = np.array(new_feature).reshape(-1, 1)
        self.test_x = np.hstack((self.test_x, test_mod_arr))


class Train_Bayes():  # NAIVE BAYES

    def __init__(self, data):
        self.occurrences = {}  # occurences of our number in the total dataset
        self.dataset = data
        self.likelyhood = {}
        self.log_prior = np.zeros(2)  # här sparar jag ned log-prior värdet
        self.count_occurences()
        self.naive_bayes_train()

    def count_occurences(self):
        for element in self.dataset.list:
            label = element["label"]
            for number in element["text"]:
                if number not in self.occurrences:
                    self.occurrences[number] = [0, 0]  # number of occurences of each number in the different classes
                if label == 0:
                    self.occurrences[number][0] += 1
                elif label == 1:
                    self.occurrences[number][1] += 1

    def naive_bayes_train(self):
        smoothing = 1  # smoothing parameter
        sum = np.zeros(2)

        for c in range(2):  # for every class (0 and 1)
            n_doc = len(self.dataset.values)
            n_c = self.dataset.labels.count(c)  # number in the given class
            self.log_prior[c] = np.log(n_c / n_doc)

            for number in self.occurrences:  # for every unique number in dataset
                count = self.occurrences[number][c]  # how many times that number occurs in class c
                sum[c] += count + smoothing  # total occuring in class c

        for c in range(2):
            for number in self.occurrences:
                if number not in self.likelyhood:  # initlializes our log-likelyhood vector
                    self.likelyhood[number] = np.zeros(2)
                self.likelyhood[number][c] = np.log((self.occurrences[number][c] + smoothing) / sum[c])


class Train_Bayes():  # NAIVE BAYES

    def __init__(self, values, labels):
        self.occurrences = {}  # occurences of our number in the total dataset
        self.values = values
        self.labels = labels
        self.LABELS = len(set(labels))
        self.classes = list(set(self.labels))

        # self.classes = [int(element) for element in class_list]
        self.likelyhood = {}
        self.log_prior = np.zeros(self.LABELS)  # här sparar jag ned log-prior värdet
        self.count_occurences()
        self.naive_bayes_train()

    def count_occurences(self):  # Behöver göra om!!!!
        count = 0
        for row in self.values:
            label = self.labels[count]
            for number in row:
                if number not in self.occurrences:  # om det inte redan finns!
                    self.occurrences[number] = [0] * self.LABELS
                self.occurrences[number][self.classes.index(label)] += 1
            count += 1

    def naive_bayes_train(self):
        smoothing = 1  # smoothing parameter
        sum = np.zeros(self.LABELS)

        for c in range(self.LABELS):  # HÄR BLIR DET FEL !!! SKA VARA FÖR VARJE UNIK
            n_doc = len(self.values)  # antalet rader i vårt dokument som ska klassificeras
            n_c = self.labels.count(self.classes[c])  # number in the given class
            self.log_prior[c] = np.log(n_c / n_doc)

            for number in self.occurrences:  # for every unique number in dataset
                count = self.occurrences[number][c]  # how many times that number occurs in class c
                sum[c] += count + smoothing  # total occuring in class c

        for c in range(self.LABELS):
            for number in self.occurrences:
                if number not in self.likelyhood:  # initlializes our log-likelyhood vector
                    self.likelyhood[number] = np.zeros(self.LABELS)
                self.likelyhood[number][c] = np.log((self.occurrences[number][c] + smoothing) / sum[c])


def test_Bayes(model, dataset):
    values_list = model.classes

    log_prior = model.log_prior
    likelyhood = model.likelyhood
    labels = model.LABELS
    '''Input: log P(c) and log P(w|c), returns list of predicted classes for each row'''
    classified = []
    for line in dataset.values:
        summa = np.zeros(labels)
        for c in range(labels):
            summa[c] = log_prior[c]
            for number in line:
                if number in likelyhood:  # if it exists in our dictionary
                    summa[c] += likelyhood[number][c]
        classified.append(list(summa).index(max(list(summa))))  # appends the class with highest probability
    result = [values_list[prediction] for prediction in classified]
    return result


def logistic_regression(data, parameters, key=''):
    if key == 'model':  # to classify which model it belongs to
        y_train = np.array(data.train_data.models)
    else:
        y_train = np.array(data.train_data.labels)
    x_train = data.train_x
    x_test = data.test_x

    # LOGISTIC REGRESSION
    logistic_reg = LogisticRegression(solver='lbfgs', max_iter=1000, C=parameters[0])
    model = logistic_reg.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    # Return the predictions
    return y_pred, model


def random_forest(data, param, key=''):
    if key == 'model':
        y_train = np.array(data.train_data.models)
    else:
        y_train = np.array(data.train_data.labels)
    x_train = data.train_x
    x_test = data.test_x

    # create classifier
    print(param)
    rf_classifier = RandomForestClassifier(max_depth=param['max_depth'], max_features=param['max_features'],
                                           min_samples_leaf=param['min_samples_leaf'],
                                           min_samples_split=param['min_samples_split'],
                                           n_estimators=param['n_estimators'], random_state=42)

    # train the classifier
    rf_classifier.fit(x_train, y_train)

    # test the classifier
    predicted_labels = rf_classifier.predict(x_test)
    return predicted_labels, rf_classifier


def support_vector_machine(data, key=''):
    if key == 'model':
        y_train = np.array(data.train_data.models)
    else:
        y_train = np.array(data.train_data.labels)
    x_train = data.train_x_scaling
    x_test = data.test_x_scaling

    clf = svm.SVC()

    # Train the classifier on the training data
    clf.fit(x_train, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(x_test)
    return y_pred, clf


def majority_vote(predictions):
    ensemble_input = np.array(predictions).T

    # Initialize a list to store the final ensemble predictions
    final_predictions = []

    # Perform a majority vote ensemble
    for row in ensemble_input:
        unique, counts = np.unique(row, return_counts=True)
        majority_vote = unique[np.argmax(counts)]
        final_predictions.append(majority_vote)

    return final_predictions


def create_stacking_model(predictions, true_labels):
    # Combine all predictions into a NumPy array
    X = np.array(predictions).T  # Transpose to match data points with predictions

    # Initialize a meta-learner (e.g., logistic regression)
    meta_learner = LogisticRegression()

    # Train the meta-learner on the training set
    meta_learner.fit(X, true_labels)

    # Save the trained meta-learner model using pickle
    with open('meta_learner_model.pkl', 'wb') as model_file:
        pickle.dump(meta_learner, model_file)


def stacking_predictions(testdata2_predictions):
    # Load the saved meta-learner model
    with open('meta_learner_model.pkl', 'rb') as model_file:
        loaded_meta_learner = pickle.load(model_file)

    # Transpose the test data predictions to match the shape
    X_test2 = np.array(testdata2_predictions).T

    # Use the loaded meta-learner to make predictions for test-dataset2
    stacked_predictions2 = loaded_meta_learner.predict(X_test2)

    # Now, stacked_predictions2 contains the final ensemble predictions for test-dataset2
    return stacked_predictions2


def evaluate(predicted_labels, true_labels):
    confusion = confusion_matrix(true_labels, predicted_labels)
    accuracy = accuracy_score(true_labels, predicted_labels)
    print(confusion)
    print(f'Accuracy: {accuracy:.2f}')


def output(classified):  # creates the output file
    file = open("output.csv", "w")
    id = 0
    file.write('id,class\n')
    for point in classified:
        file.write(str(id) + ',' + str(point) + '\n')
        id += 1
    file.close()

def save_model(model, data, filename):
    # Combine the vectorizer and model into a dictionary
    combined_data = {
        'vectorizer': data.vectorizer,
        'model': model,
        'pca': data.pca,
        'scaling': data.scaler,
    }
    # Save the combined data to a single file
    pickle.dump(combined_data, open(filename, 'wb'))


def load_model(filename, testdata, domain_filename=''):
    with open(filename, 'rb') as file:
        combined_data = pickle.load(file)

    # Access the vectorizer and model from the dictionary
    loaded_vectorizer = combined_data['vectorizer']
    loaded_model = combined_data['model']
    loaded_pca = combined_data['pca']
    loaded_scaling = combined_data['scaling']
    # Transform new test data
    testdata_vector = VectorRepresentation(None, testdata, vectorizer=loaded_vectorizer, pca=loaded_pca,
                                           scaler=loaded_scaling)

    # When we need to load the file with the model that predicts models!
    if domain_filename != '':  # HERE WE PREDICT NEW MODELS
        model_predictor, model_testdata = load_model(domain_filename, testdata)
        predicted_models = model_predictor.predict(model_testdata.test_x)  # predicts models based on our testdata
        testdata_vector.add_new_feature(predicted_models)

    return loaded_model, testdata_vector


def create_model_predictors(model_trainer, filename):
    if model_trainer == '1':
        print('Predicts models based on dataset 1')
        model_training, model_test = choose_dataset('1', 'n')
        parameters = [10, 'l2']
    elif model_trainer == '2':
        print('Predicts models based on dataset 2')
        model_training, model_test = choose_dataset('2', 'n')
        parameters = [1, 'l2']
    else:
        print('Predicts models based on dataset 3')
        model_training, model_test = choose_dataset('3', 'n')
        parameters = [1, 'l2']

    # predict models based on logistic regression
    data = VectorRepresentation(model_training, model_test)
    model_predictions, model = list(logistic_regression(data, parameters, 'model'))  # predicts models for the dataset
    save_model(model, data, filename)  # Saves the model in predict_models
    evaluate(model_predictions, model_test.models)  # evaluates the model
    return model_predictions


def create_text_predictors(choice, training, test, filename, method='',smote=None):
    if smote == None:
        data =VectorRepresentation(training, test)
    else:
        data = VectorRepresentation(training, test, 'smote')  # smote training dataset
    if method == '':
        print('\nCREATE LOGISTIC REGRESSION MODEL TRAINED ON DATASET:', choice)
        # BASED ON DATASET; HAVE DIFFERENT HYPERPARAMETERS
        if choice == '1':
            parameters = [10, 'l2']
        if choice == '2':
            parameters = [0.001, 'l2']
        if choice == '3':
            parameters = [1, 'l2']
        data.add_new_feature(test.labels)
        pred_logistic, logistic_model = list(logistic_regression(data, parameters))
        save_model(logistic_model, data, filename)
        print('Saved model into file:', filename)

    elif method == 'svm':
        print('\nCREATE SVM MODEL TRAINED ON DATASET:', choice)
        data.add_new_feature(test.labels)
        pred_svm, svm_model = list(support_vector_machine(data))
        save_model(svm_model, data, filename)
        print('Saved model into file:', filename)

    elif method == 'random forest':
        print('CREATE RANDOM FOREST MODEL TRAINED ON DATASET:', choice)
        if choice == '1':
            parameters = {'max_depth': None, 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 2,
                          'n_estimators': 200}
        else:
            parameters = {'max_depth': 20, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 10,
                          'n_estimators': 10}
        data.add_new_feature(test.labels)
        pred_forest, forest_model = list(random_forest(data, parameters))
        save_model(forest_model, data, filename)
        print('Saved model into file:', filename)
    else:
        pass


def choose_dataset(choice):
    if choice == '1':
        lista1 = readfile(path1)
        training = Dataset(lista1)
        test = Dataset(lista1)
    elif choice == '2':
        lista2 = readfile(path2)
        training = Dataset(lista2)
        test = Dataset(lista2)
    elif choice == '3':
        lista1 = readfile(path1)
        lista2 = readfile(path2)
        lista3 = lista1 + lista2
        training = Dataset(lista3)
        test = Dataset(lista3)
    else:
        lista1 = readfile(path1)
        lista2 = readfile(path2)
        lista3 = lista1 + lista2
        training = Dataset(lista3)
        test_list = readfile(kaggle_test_set)
        test = Dataset(test_list)
    return training, test


def choose_dataset1(choice):
    if choice == '1':
        training = Dataset(readfile(path3))
        test = Dataset(readfile(path4))
    elif choice == '2':
        training = Dataset(readfile(path5))
        test = Dataset(readfile(path6))
    else:
        training = Dataset(readfile(path7))
        test = Dataset(readfile(path8))
    return training, test



if __name__ == '__main__':
    # 1) create domain classification model
    # model_choice = '2'  # choose 1,2,3 to decide on which dataset the domain predictor should be trained on
    # filename = 'domain2.sav'  # choose file where the model should be saved
    # create_model_predictors(model_choice, filename)

    # 2) create text classification model
    method = 'svm'                                      # write svm, random forest. default is logistic regression
    choice = '3'                                        # choose between dataset 1,2 or 3, or testdata to classify text
    full_dataset = ''                                   # "yes" for training on full dataset
    filename = 'small_svm_3.sav'                        # choose here where to save the created model!
    smote = True if not choice == '1' else None         # only use smote for domain2 and domain1+domain2

    if full_dataset == 'yes':
        print('CREATES MODEL ON TRAINED ON THE FULL DATASET')
        training, test = choose_dataset(choice)
    else:
        print('CREATES MODEL TRAINED ON 80% OF THE DATASET')
        training, test = choose_dataset1(choice)  # only to use small datasets

    if method == 'svm':
        create_text_predictors(choice, training, test, filename, 'svm', smote)
    elif method == 'random forest':
        create_text_predictors(choice, training, test, filename, 'random forest', smote)
    else:   # logistic regression
        create_text_predictors(choice, training, test, filename, '', smote)


    # 3) Choose test data
    choice = '4'  # choose the domain the testing should be made based on
    full_dataset = 'yes'  # choose if to test on full dataset or not
    if full_dataset == 'yes':
        training_data, test_data = choose_dataset(choice)  # the full files!
    else:
        training_data, test_data = choose_dataset1(choice) # 20 % of the data

    # 4) Load models and evaluate

    print('Naive Bayes')
    model = Train_Bayes(training_data.values, training_data.labels)
    predictions = test_Bayes(model,test_data)
    # evaluate(predictions, test_data.labels)

    print('Random forest 1')
    forest1, forest_test1 = load_model('small_forest_1.sav', test_data, 'domain1.sav')
    forest_pred_1 = forest1.predict(forest_test1.test_x)
    #evaluate(forest_pred_1, test_data.labels)

    print('\nRandom forest 2')
    forest2, forest_test2 = load_model('small_forest_2.sav', test_data, 'domain2.sav')
    forest_pred_2 = forest2.predict(forest_test2.test_x)
    #evaluate(forest_pred_2, test_data.labels)

    print('\nRandom forest 3')
    forest3, forest_test3 = load_model('small_forest_3.sav', test_data, 'domain3.sav')
    forest_pred_3 = forest3.predict(forest_test3.test_x)
    # evaluate(forest_pred_3, test_data.labels)

    print('\nLogistic 1:')
    logistic1, testdata1 = load_model('small_logistic_1.sav', test_data, 'domain1.sav')
    log_pred_1 = logistic1.predict(testdata1.test_x)
    # evaluate(log_pred_1, test_data.labels)

    print('\nLogistic 2:')
    logistic2, testdata2 = load_model('small_logistic_2.sav', test_data, 'domain2.sav')  # model trained on dataset 1
    log_pred_2 = logistic2.predict(testdata2.test_x)
    # evaluate(log_pred_2, test_data.labels)

    print('\nLogistic 3:')
    logistic3, testdata3 = load_model('small_logistic_3.sav', test_data, 'domain3.sav')  # model trained on dataset 1
    log_pred_3 = logistic3.predict(testdata3.test_x)
    # evaluate(log_pred_3, test_data.labels)

    print('\nSVM 1:')
    svm1, test1 = load_model('small_svm_1.sav', test_data, 'domain1.sav')
    svm_pred_1 = svm1.predict(test1.test_x_scaling)
    # evaluate(svm_pred_1, test_data.labels)

    print('\nSVM 2:')
    svm2, test2 = load_model('small_svm_2.sav', test_data, 'domain2.sav')
    svm_pred_2 = svm2.predict(test2.test_x_scaling)
    # evaluate(svm_pred_2, test_data.labels)

    print('\nSVM 3:')
    svm3, test3 = load_model('small_svm_3.sav', test_data, 'domain3.sav')
    svm_pred_3 = svm3.predict(test2.test_x_scaling)
    # evaluate(svm_pred_3, test_data.labels)

    # Majority Voting
    print('\nMajority Voting only with logistic:')
    predictions = [log_pred_1,log_pred_2,log_pred_3]
    pred = majority_vote(predictions)
    evaluate(pred, test_data.labels)
    #output(pred)

    # Log+Random forest
    print('Majority Voting with log+random forest :')
    predictions = [log_pred_1, log_pred_2, log_pred_3,forest_pred_1,forest_pred_2,forest_pred_3]
    pred = majority_vote(predictions)
    evaluate(pred, test_data.labels)

    # Log+Random forest + SVM
    print('Majority Voting with log+random forest+svm :')
    predictions = [log_pred_1, log_pred_2, log_pred_3,forest_pred_1,forest_pred_2,forest_pred_3,svm_pred_1,svm_pred_2,svm_pred_3]
    pred = majority_vote(predictions)
    evaluate(pred, test_data.labels)

    # Stacking ensamble method
    print('Stacking with all')
    predictions = [svm_pred_1,svm_pred_2,svm_pred_3]
    # Split the data into a training set and a validation set
    if choice == '1' or choice == '2' or choice == '3':
        X_train, y_train, X_valid, y_valid = split_predictions(predictions,test_data.labels)
        print(len(X_valid))
        create_stacking_model(X_train, y_train)
        pred = stacking_predictions(X_valid)
        evaluate(pred, y_valid)
    else: # only load stacking model
        pred = stacking_predictions(test_data)
        output(pred)



